spring:
  profiles:
    active: EN, cat, dev
guru:
  constructor:
    config:
      username: guru_username_constructor
      password: guru_password_constructor
      jdbc_url: guru_jdbc_url_constructor
  property:
    config:
      username: guru_username_property
      password: guru_password_property
      jdbc_url: guru_jdbc_url_property